Vagrant.require_version ">= 1.9.1"

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.3"
  config.vm.hostname = "demo-vagrant-host"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
  end

  config.vm.provider "virtualbox" do |v|
    v.name = 'ansible-demo'
  end
end
